--1.	Create aws_stage in staging_layer
CREATE OR REPLACE STAGE staging_layer.aws_stage
    URL = 's3://course-data-warehouse-viki/DataWarehouseAndSnowflake/'
    CREDENTIALS = (
        AWS_KEY_ID = '...'
        AWS_SECRET_KEY = '....'
        );


--
CREATE OR REPLACE STAGE staging_layer.local_stage;

--to see all the files
LIST @staging_layer.aws_stage;

--2.Create csv formagt
--WHAT IS THE TYPE..
CREATE OR REPLACE FILE FORMAT STAGING_LAYER.CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1;

--3.CREATE RAW TABLE
--WE ADD STRING BECAUSE THOSE ARE ALL OUR RAW DATA AND WE NEED THEM ALL TO BE SORTED HERE AND TO USE THEM 
CREATE OR REPLACE TABLE RAW_LAYER.SALES_ORDERS_RAW(
    ORDER_ID STRING ,
    CUSTOMER_ID STRING,
    PRODUCT_ID STRING,
    ORDER_DATE STRING,
    AMOUNT STRING,
    PROFIT STRING,
    QUANTITY STRING,
    CATEGORY STRING,
    SUBCATEGORY STRING
);

--4. Load data from large_orders.csv from s3 to snowflake table

COPY INTO RAW_LAYER.SALES_ORDERS_RAW
    FROM @STAGING_LAYER.AWS_STAGE
    FILES = ('large_orders.csv')
    FILE_FORMAT = STAGING_LAYER.CSV_FORMAT
    ON_ERROR = 'CONTINUE';

SELECT * FROM RAW_LAYER.SALES_ORDERS_RAW;


--5. create cleansed table

CREATE OR REPLACE TRANSIENT TABLE CLEANSED_LAYER.SALES_ORDERS_CLEAN AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    TO_DATE(ORDER_DATE,'YYYY-MM-DD')AS ORDER_DATE,
    TO_DECIMAL(AMOUNT,10,2) AS AMOUNT,
    TO_DECIMAL(PROFIT,10,2) AS PROFIT,
    TRY_TO_NUMBER(QUANTITY) AS QUANTITY,
    INITCAP(CATEGORY)AS CATEGORY,
    INITCAP(SUBCATEGORY) AS SUBCATEGORY
FROM RAW_LAYER.SALES_ORDERS_RAW;

SELECT * FROM CLEANSED_LAYER.SALES_ORDERS_CLEAN;

--6. MASK, RULE THAT CHANGES THE VALUE OF THE COLUMN DEPENDING ON THE PERSONS ROLE-- IT'S AN INFORMATION SECUTIRY

CREATE OR REPLACE MASKING POLICY CLEANSED_LAYER.MASKED_AMOUNT -- MASKED AMOUND THE NAME OF THE RULE
    AS (VAL DECIMAL(10,2))
    RETURNS DECIMAL(10,2) ->
    CASE
        WHEN CURRENT_ROLE() = 'FINANCE DEPARTMENT' THEN VAL -- CHECK THE ROLE
        ELSE NULL
    END;

ALTER TABLE CLEANSED_LAYER.SALES_ORDERS_CLEAN
    MODIFY COLUMN AMOUNT
    SET MASKING POLICY CLEANSED_LAYER.MASKED_AMOUNT;

    --7 CREATE TABLE FOR MV DROM BASE TABLE

    CREATE OR REPLACE TRANSIENT TABLE CLEANSED_LAYER.SALES_ORDERS_MV_READY AS
    SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    ORDER_DATE,
    AMOUNT,
    PROFIT, 
    QUANTITY,
    CATEGORY,
    SUBCATEGORY
    FROM CLEANSED_LAYER.SALES_ORDERS_CLEAN;

    SELECT * FROM CLEANSED_LAYER.SALES_ORDERS_MV_READY; -- THE MASKING IS BEING USED HERE FRO THNE AMOUNT

    --8 PRE-COMPUTE TOTAL SALES PER CATEGORY FOR DAST BI ACCSESS
    CREATE OR REPLACE MATERIALIZED VIEW BUSINESS_LAYER.PROFIT_SUMMARY_MV AS 
    SELECT 
        CATEGORY,
        SUM(PROFIT) AS PROFIT
    FROM CLEANSED_LAYER.SALES_ORDERS_MV_READY
    GROUP BY CATEGORY;

    SELECT * FROM BUSINESS_LAYER.PROFIT_SUMMARY_MV;

    --9 CREATE A LOGICAL VIEW

    CREATE OR REPLACE VIEW PRESENTATION_LAYER.V_PROFIT_DASHBOARD AS
    SELECT
        CATEGORY,
        ROUND(PROFIT/SUM(PROFIT) OVER(),3) AS SHARE_OF_TOTAL
    FROM BUSINESS_LAYER.PROFIT_SUMMARY_MV
    ORDER BY PROFIT;

    SELECT * FROM PRESENTATION_LAYER.V_PROFIT_DASHBOARD;

    --11
    --JSON
CREATE OR REPLACE FILE FORMAT STAGING_LAYER.JSON_FORMAT
  TYPE = JSON
  STRIP_OUTER_ARRAY = TRUE -- WHEN WE USE semi-structured data
  ENABLE_OCTAL      = FALSE; --forbids nums that starts with 0


CREATE OR REPLACE TABLE raw_layer.reviews_raw (
  raw_record VARIANT 
);

COPY INTO raw_layer.reviews_raw(raw_record)
  FROM @STAGING_LAYER.AWS_STAGE
  FILES = ('large_customer_reviews.json')
  FILE_FORMAT = staging_layer.json_format
  ON_ERROR    = 'CONTINUE';
SELECT * FROM raw_layer.reviews_raw;

--unpack
CREATE OR REPLACE TABLE cleansed_layer.reviews AS
SELECT
  raw_record:"review_id"     ::INT     AS review_id,
  raw_record:"customer_id"   ::STRING  AS customer_id,
  raw_record:"review_data"."rating"   ::INT     AS rating,
  raw_record:"review_data"."comment"  ::STRING  AS comment,
  raw_record:"review_data"."verified" ::BOOLEAN AS verified
FROM raw_layer.reviews_raw;


SELECT * 
  FROM cleansed_layer.reviews;


--12

CREATE OR REPLACE ROW ACCESS POLICY CLEANSED_LAYER.CATEG_FILTER
    AS(CAT STRING())
    RETURNS BOOLEAN ->
    CASE
        WHEN UPPER(TRIM(CAT)) = UPPER(CURRENT_ROLE()) THEN TRUE
        WHEN CURRENT_ROLE() = 'FURNITURE' THEN TRUE
        ELSE FALSE
    END;

    --DROP ALL ACCESES
ALTER TABLE CLEANSED_LAYER.SALES_ORDERS_CLEAN
    DROP ALL ROW ACCESS POLICIES;

ALTER TABLE CLEANSED_LAYER.SALES_ORDERS_CLEAN
    ADD ROW ACCESS POLICY CLEANSED_LAYER.CATEG_FILTER
    ON(CATEGORY);

SELECT * FROM CLEANSED_LAYER.SALES_ORDERS_CLEAN;


--13 RESTORE QUERY

SELECT * FROM CLEANSED_LAYER.SALES_ORDERS_CLEAN AT(OFFSET => - 600);  --TIMETRAVEL

--14 CHECK STORAGE 

SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    ACTIVE_BYTES/1024/1024 AS SIZE_MB
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
WHERE TABLE_SCHEMA IN ('ROW_LAYER','CLEANSING_LAYER','BUSINESS_LAYER');

--15 RECOURCE MONITORING

CREATE OR REPLACE RESOURCE MONITOR TEAM_LIMIT
    WITH CREDIT_QUOTA = 50
    TRIGGERS ON 90 PERCENT DO SUSPEND;


       --GIVING ROLES
GRANT SELECT ON ALL TABLES IN SCHEMA SALES_DB_NOV.CLEANSED_LAYER TO ROLE ANALYST_ROLE_NOV;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASES SALES_DB_NOV TO ROLE ALANYST_ROLE_NOV;
GRANT USAGE ON FUTURE TABLES IN SCHEMA SALES_DB_NOV.CLEANSED_LAYER TO ROLE ANALYST_ROLE_NOV;