--creatin a role, giving it;s privileges, assigning it to a user and using it
CREATE ROLE data_engineer;
GRANT ROLE ACCOUNTADMIN TO ROLE data_engineer;
SELECT CURRENT_ROLE();
GRANT ROLE data_engineer TO USER crazytori;
USE ROLE data_engineer;

-- Warehouse for loading
CREATE WAREHOUSE IF NOT EXISTS EXAM_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS AIRFLOW_EXAM_DEC;

-- Schemas
CREATE SCHEMA AIRFLOW_EXAM_DEC.STAGING_LAYER;
CREATE SCHEMA AIRFLOW_EXAM_DEC.CLEANSED_LAYER;
CREATE SCHEMA AIRFLOW_EXAM_DEC.BUSINESS_LAYER;
CREATE SCHEMA AIRFLOW_EXAM_DEC.ANALYTICS_LAYER;


CREATE SCHEMA AIRFLOW_EXAM_DEC.PRESENTATION;

CREATE FILE FORMAT AIRFLOW_EXAM_DEC.STAGING_LAYER.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1;



CREATE OR REPLACE STAGE  AIRFLOW_EXAM_DEC.STAGING_LAYER.RETAIL_S3_STAGE
    URL = 's3://course-data-warehouse-viki/OutputExam/'
    CREDENTIALS = (
        AWS_KEY_ID = 'AKIAYZE6FEMCFECVD7MR'
        AWS_SECRET_KEY = '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'
    )
    FILE_FORMAT = AIRFLOW_EXAM_DEC.STAGING_LAYER.CSV_FORMAT;

CREATE TABLE AIRFLOW_EXAM_DEC.CLEANSED_LAYER.CLEANED_SALES (
    sales_id        INT,
    product_id      INT,
    region          STRING,
    quantity        INT,
    price           NUMERIC(10, 2),
    timestamp       DATE,
    discount     NUMERIC(10, 2),
    order_status STRING
);

CREATE TABLE AIRFLOW_EXAM_DEC.CLEANSED_LAYER.CLEANED_PRODUCTS (
    product_id      INT,
    category        STRING,
    brand           STRING,
    rating          NUMERIC(10, 2),
    in_stock        BOOLEAN,
    launch_date     DATE
);

COPY INTO AIRFLOW_EXAM_DEC.CLEANSED_LAYER.CLEANED_SALES
FROM @AIRFLOW_EXAM_DEC.STAGING_LAYER.RETAIL_S3_STAGE
FILES = ('cleaned_sales.csv'),
ON_ERROR = 'CONTINUE';

SELECT * FROM AIRFLOW_EXAM_DEC.CLEANSED_LAYER.CLEANED_SALES;

COPY INTO AIRFLOW_EXAM_DEC.CLEANSED_LAYER.CLEANED_PRODUCTS
FROM @AIRFLOW_EXAM_DEC.STAGING_LAYER.RETAIL_S3_STAGE
FILES = ('cleaned_products.csv'),
ON_ERROR = 'CONTINUE';
select * from AIRFLOW_EXAM_DEC.CLEANSED_LAYER.CLEANED_PRODUCTS


 -- Build Star Schema in Snowflake
-- Create STAR.DIM_DATE, STAR.DIM_PRODUCT, and STAR.FACT_SALES from CLEANSED_LAYER.SALES_CLEAN.



CREATE OR REPLACE TABLE AIRFLOW_EXAM_DEC.BUSINESS_LAYER.DIM_DATE (
    date_key INT PRIMARY KEY,
    full_date DATE NOT NULL,
    day_name STRING NOT NULL,
    month INT NOT NULL,
    month_name STRING NOT NULL,
    quarter INT NOT NULL,
    year INT NOT NULL
);

INSERT INTO AIRFLOW_EXAM_DEC.BUSINESS_LAYER.DIM_DATE
SELECT DISTINCT
    TO_CHAR(timestamp, 'YYYYMMDD')::INT AS date_key,
    timestamp::DATE AS full_date,
    DAYNAME(timestamp)                 AS day_name,
    MONTH(timestamp) AS month,
    MONTHNAME(timestamp) AS month_name,
    QUARTER(timestamp) AS quarter,
    YEAR(timestamp) AS year
FROM AIRFLOW_EXAM_DEC.CLEANSED_LAYER.CLEANED_SALES;

-- TRUNCATE TABLE AIRFLOW_EXAM_DEC.BUSINESS_LAYER.DIM_DATE;

-- SELECT * FROM AIRFLOW_EXAM_DEC.BUSINESS_LAYER.DIM_DATE;

CREATE OR REPLACE TABLE AIRFLOW_EXAM_DEC.BUSINESS_LAYER.DIM_PRODUCT (
    product_id INT PRIMARY KEY,
    brand STRING NOT NULL,
    category STRING NOT NULL,
    rating NUMBER(4,2),
    in_stock        BOOLEAN,
    launch_date     DATE
);

INSERT INTO AIRFLOW_EXAM_DEC.BUSINESS_LAYER.DIM_PRODUCT
SELECT DISTINCT
    product_id,
    brand,
    category,
    rating,
    in_stock,
    launch_date
FROM AIRFLOW_EXAM_DEC.CLEANSED_LAYER.CLEANED_PRODUCTS;


-- SELECT * FROM AIRFLOW_EXAM_DEC.BUSINESS_LAYER.DIM_PRODUCT;

CREATE OR REPLACE TABLE AIRFLOW_EXAM_DEC.BUSINESS_LAYER.FACT_SALES (
    sales_id INT PRIMARY KEY,
    product_id INT NOT NULL,
    date_key INT NOT NULL,
    region STRING NOT NULL,
    quantity INT NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    discount NUMERIC(10,2) DEFAULT 0,
    total_sales NUMERIC(10,2) NOT NULL,
    order_status STRING NOT NULL,
    FOREIGN KEY (product_id) REFERENCES AIRFLOW_EXAM_DEC.BUSINESS_LAYER.DIM_PRODUCT(product_id),
    FOREIGN KEY (date_key) REFERENCES AIRFLOW_EXAM_DEC.BUSINESS_LAYER.DIM_DATE(date_key)
);

INSERT INTO AIRFLOW_EXAM_DEC.BUSINESS_LAYER.FACT_SALES
SELECT
    s.sales_id,
    s.product_id,
    TO_CHAR(s.timestamp, 'YYYYMMDD')::INT AS date_key,  -- links to DIM_DATE
    s.region,
    s.quantity,
    s.price,
    s.discount,
    s.quantity * s.price * (1 - COALESCE(s.discount,0)) AS total_sales,
    s.order_status
FROM AIRFLOW_EXAM_DEC.CLEANSED_LAYER.CLEANED_SALES s;


SELECT * FROM AIRFLOW_EXAM_DEC.BUSINESS_LAYER.FACT_SALES

SHOW TABLES IN SCHEMA AIRFLOW_EXAM_DEC.BUSINESS_LAYER;


-- Create Materialized Analytical Views
-- Create materialized views under PRESENTATION schema: MV_SALES_BY_REGION_MONTH, MV_TOP_PRODUCTS_BY_REVENUE, MV_REVENUE_TREND, MV_CATEGORY_PERFORMANCE.



CREATE OR REPLACE MATERIALIZED VIEW AIRFLOW_EXAM_DEC.ANALYTICS_LAYER.MV_SALES_BY_REGION_MONTH AS
SELECT
    region,
    MONTHNAME(TO_DATE(date_key::STRING, 'YYYYMMDD')) AS month,
    YEAR(TO_DATE(date_key::STRING, 'YYYYMMDD')) AS year,
    COUNT(sales_id) AS total_orders,
    SUM(total_sales) AS total_revenue
FROM AIRFLOW_EXAM_DEC.BUSINESS_LAYER.FACT_SALES
GROUP BY
     region,
     month,
     year;


SELECT * FROM AIRFLOW_EXAM_DEC.ANALYTICS_LAYER.MV_SALES_BY_REGION_MONTH
ORDER BY YEAR DESC, MONTH;

--

CREATE OR REPLACE MATERIALIZED VIEW AIRFLOW_EXAM_DEC.ANALYTICS_LAYER.MV_TOP_PRODUCTS_BY_REVENUE AS
SELECT
    product_id,
    sum(total_sales) AS total_revenue,
    CASE
        WHEN SUM(total_sales) > 25000 THEN 'TOP REVENUE'
        WHEN SUM(total_sales) BETWEEN 15000 AND 25000 THEN 'MIDDLE REVENUE'
        ELSE 'LOW REVENUE'
    END AS producst_by_revenue
FROM AIRFLOW_EXAM_DEC.BUSINESS_LAYER.FACT_SALES
GROUP BY product_id;


SELECT * FROM AIRFLOW_EXAM_DEC.ANALYTICS_LAYER.MV_TOP_PRODUCTS_BY_REVENUE
order by total_revenue desc;

-- MV_REVENUE_TREND

CREATE OR REPLACE MATERIALIZED VIEW AIRFLOW_EXAM_DEC.ANALYTICS_LAYER.MV_REVENUE_TREND AS
SELECT
    YEAR(TO_DATE(date_key::STRING, 'YYYYMMDD')) AS year,
    MONTHNAME(TO_DATE(date_key::STRING, 'YYYYMMDD')) AS month,
    SUM(total_sales) AS total_revenue
FROM AIRFLOW_EXAM_DEC.BUSINESS_LAYER.FACT_SALES
group by year, month;

 -- DAY(TO_DATE(date_key::STRING, 'YYYYMMDD')) AS DAY,    day

SELECT * FROM AIRFLOW_EXAM_DEC.ANALYTICS_LAYER.MV_REVENUE_TREND
ORDER BY year, month;


---


CREATE or replace TABLE AIRFLOW_EXAM_DEC.ANALYTICS_LAYER.PRODUCT_SALES AS
    SELECT
        p.category,
        s.timestamp,
        SUM(s.quantity) AS total_quantity,
        SUM(s.quantity * s.price * (1 - COALESCE(s.discount,0))) AS total_sales,
    FROM AIRFLOW_EXAM_DEC.CLEANSED_LAYER.CLEANED_PRODUCTS p
    JOIN AIRFLOW_EXAM_DEC.CLEANSED_LAYER.CLEANED_SALES s
    ON p.product_id = s.product_id
    group by p.category,s.timestamp;


-- SELECT * FROM AIRFLOW_EXAM_DEC.ANALYTICS_LAYER.PRODUCT_SALES
-- WHERE category = 'clothing'
-- ORDER BY year, month;



CREATE OR REPLACE MATERIALIZED VIEW AIRFLOW_EXAM_DEC.ANALYTICS_LAYER.MV_CATEGORY_PERFORMANCE AS
SELECT
    category,
    YEAR(TO_DATE(timestamp::STRING, 'YYYY-MM-DD')) AS year,
    MONTHNAME(TO_DATE(timestamp::STRING, 'YYYY-MM-DD')) AS month,
    total_quantity,
    total_sales
from AIRFLOW_EXAM_DEC.ANALYTICS_LAYER.PRODUCT_SALES;

 SELECT * FROM AIRFLOW_EXAM_DEC.ANALYTICS_LAYER.MV_CATEGORY_PERFORMANCE;