aws_conn_id : aws_conn_id

s3:
  bucket: course-data-warehouse-viki
  folder: Exam/
  output_folder : OutputExam

snowflake:
  conn_id: my_snowflake_conn
  database: AIRFLOW_EXAM_DEC
  targets:
    sales:
      schema: CLEANSED_LAYER
      table: CLEANED_SALES
    products:
      schema: CLEANSED_LAYER
      table: CLEANED_PRODUCTS
    merged:
      schema: ANALYTICS_LAYER
      table: product_sales