CREATE DATABASE SALES_DB_NOV_AIRFLOW;
USE DATABASE SALES_DB_NOV_AIRFLOW;
CREATE SCHEMA CLEANSED_LAYER;
CREATE SCHEMA PRESENTATION_LAYER;

CREATE OR REPLACE TABLE SALES_DB_NOV_AIRFLOW.CLEANSED_LAYER.SALES(
    ORDER_ID STRING,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    ORDER_DATE DATE,
    AMOUNT NUMERIC(10, 2),
    QUANTITY INT,
    DISCOUNT NUMERIC(10,2),
    PROFIT NUMERIC(10,2),
    TOTAL_REVENUE NUMERIC(10,2)
);

CREATE TABLE SALES_DB_NOV_AIRFLOW.CLEANSED_LAYER.CUSTOMERS(
    CUSTOMER_ID INT,
    NAME STRING,
    EMAIL STRING,
    SIGNUP_DATE DATE
);

CREATE TABLE SALES_DB_NOV_AIRFLOW.CLEANSED_LAYER.PRODUCTS(
    PRODUCT_ID INT,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE NUMERIC(10, 2)
);

CREATE TABLE SALES_DB_NOV_AIRFLOW.PRESENTATION_LAYER.MONTLY_SALES_SUMMARY(
    ORDER_DATE DATE,
    UNIQUE_CUSTOMERS INT,
    TOTAL_SALES NUMERIC(10,2)
);

SELECT * FROM SALES_DB_NOV_AIRFLOW.PRESENTATION_LAYER.MONTHLY_SALES_SUMMARY;