aws_conn_id: aws_conn_id

s3:
  bucket: course-data-warehouse-viki
  folder: AirflowPipeline/

snowflake:
  conn_id: my_snowflake_conn
  database: SALES_DB_NOV_AIRFLOW
  targets:
    sales:
      schema: CLEANSED_LAYER
      table: sales
    customers:
      schema: CLEANSED_LAYER
      table: customers
    products:
      schema: CLEANSED_LAYER
      table: products
    monthly_sales:
      schema: presentation_layer
      table: monthly_sales_summary
    customer_segment:
      schema: business_layer
      table: segment_customers
    forecast_sales:
      schema: presentation_layer
      table: monthly_sales_forecast
    detect_sales_anomalies:
      schema: presentation_layer
      table: sales_anomalies


