CREATE DATABASE SALES_DATAVASE_NOV;

CREATE SCHEMA SALES_DATAVASE_NOV.STAGING_LAYER;
CREATE SCHEMA SALES_DATAVASE_NOV.RAW_LAYER;
CREATE SCHEMA SALES_DATAVASE_NOV.CLEANSED_LAYER;
CREATE SCHEMA SALES_DATAVASE_NOV.ANALYTICS_LAYER;


CREATE FILE FORMAT SALES_DATAVASE_NOV.STAGING_LAYER.CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1;

CREATE STAGE SALES_DATAVASE_NOV.STAGING_LAYER.AWS_STAGE
url = 's3://course-data-warehouse-viki/ETLANDELT/'
    credentials=(aws_key_id='', aws_secret_key= '');

LIST @SALES_DATAVASE_NOV.STAGING_LAYER.AWS_STAGE;

CREATE OR REPLACE TABLE SALES_DATAVASE_NOV.RAW_LAYER.RAW_SALES(
    	order_id STRING,
    	customer_id INT,
    	order_date STRING,
    	amount NUMERIC,
    	quantity INT,
    	product_id INT,
    	discount NUMERIC,
    	profit NUMERIC,
    	shipping_days INT
);

CREATE OR REPLACE TABLE SALES_DATAVASE_NOV.RAW_LAYER.RAW_CUSTOMER(
    	customer_id STRING,
    	CUSTOMER_NAME STRING,
        EMAIL STRING,
        SIGNUP_DATE STRING

);

CREATE OR REPLACE TABLE SALES_DATAVASE_NOV.RAW_LAYER.RAW_PRODUCTS(
    	PRODUCT_ID STRING,
        PRODUCT_NAME STRING,
        CATEGORY STRING,
        PRICE STRING

);


--ADD DATA

COPY INTO SALES_DATAVASE_NOV.RAW_LAYER.RAW_SALES
FROM @SALES_DATAVASE_NOV.STAGING_LAYER.AWS_STAGE
FILE_FORMAT = SALES_DATAVASE_NOV.STAGING_LAYER.CSV_FORMAT
FILES =('sales_data.csv')
ON_ERROR = 'CONTINUE';

COPY INTO SALES_DATAVASE_NOV.RAW_LAYER.RAW_CUSTOMER
FROM @SALES_DATAVASE_NOV.STAGING_LAYER.AWS_STAGE
FILE_FORMAT = SALES_DATAVASE_NOV.STAGING_LAYER.CSV_FORMAT
FILES =('customer_data.csv')
ON_ERROR = 'CONTINUE';

COPY INTO SALES_DATAVASE_NOV.RAW_LAYER.RAW_PRODUCTS
FROM @SALES_DATAVASE_NOV.STAGING_LAYER.AWS_STAGE
FILE_FORMAT = SALES_DATAVASE_NOV.STAGING_LAYER.CSV_FORMAT
FILES =('product_data.csv')
ON_ERROR = 'CONTINUE';

--check

SELECT * FROM SALES_DATAVASE_NOV.RAW_LAYER.RAW_CUSTOMER;

---TRANSFORM

CREATE TRANSIENT TABLE SALES_DATAVASE_NOV.CLEANSED_LAYER.CLEANED_SALES AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    TO_DATE(ORDER_DATE, 'DD-MM-YY') AS ORDER_DATE,
    TO_DECIMAL(AMOUNT,10,2) AS AMOUNT,
    TRY_TO_NUMBER(QUANTITY) AS QUANTITY,
    PRODUCT_ID,
    TO_DECIMAL(DISCOUNT,10,2) AS DISCOUNT,
    TO_DECIMAL(PROFIT,10,2) AS PROFIT,
    COALESCE(SHIPPING_DAYS,0) AS SHIPPING_DAYS
FROM SALES_DATAVASE_NOV.RAW_LAYER.RAW_SALES
WHERE ORDER_DATE IS NOT NULL;

CREATE TRANSIENT TABLE SALES_DATAVASE_NOV.CLEANSED_LAYER.CLEANED_CUSTOMER AS
SELECT
    CUSTOMER_ID,
    LOWER(CUSTOMER_NAME) AS CUSTOMER_NAME,
    EMAIL,
    TO_DATE(SIGNUP_DATE,'YYYY-MM-DD') AS SIGNUP_DATE
FROM SALES_DATAVASE_NOV.RAW_LAYER.RAW_CUSTOMER;

CREATE TRANSIENT TABLE SALES_DATAVASE_NOV.CLEANSED_LAYER.CLEANED_PRODUCTS AS
SELECT
    PRODUCT_ID,
    LOWER(PRODUCT_NAME) AS PRODUCT_NAME,
    LOWER(CATEGORY) AS CATEGORY,
    TO_DECIMAL(PRICE,10,2) AS PRICE
FROM SALES_DATAVASE_NOV.RAW_LAYER.RAW_PRODUCTS
WHERE PRICE >0;

--check
SELECT * FROM SALES_DATAVASE_NOV.CLEANSED_LAYER.CLEANED_PRODUCTS;

--perform transformation i the analysis layer


CREATE TABLE SALES_DATAVASE_NOV.ANALYTICS_LAYER.SALES_AGGREGATE AS
SELECT
    CUSTOMER_ID,
    DATE_TRUNC('month',ORDER_DATE) AS SALES_MONTH,
    COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT,
    SUM(AMOUNT * QUANTITY) AS TOTAL_REVENUE
FROM SALES_DATAVASE_NOV.CLEANSED_LAYER.CLEANED_SALES
GROUP BY CUSTOMER_ID,SALES_MONTH;

CREATE OR REPLACE MATERIALIZED VIEW SALES_DATAVASE_NOV.ANALYTICS_LAYER.MV_CUSTOMER_SEGMENT AS
SELECT
    CUSTOMER_ID,
    SUM(AMOUNT * QUANTITY) AS TOTAL_SPEND,
    CASE
        WHEN SUM(AMOUNT * QUANTITY) >10000 THEN 'HIGH VALUE'
        WHEN SUM(AMOUNT * QUANTITY) BETWEEN 5000 AND 10000 THEN 'MEDIUM VALUE'
        ELSE 'LOW VALUE'
    END AS CUSTOMER_CATEGORY
FROM SALES_DATAVASE_NOV.CLEANSED_LAYER.CLEANED_SALES
GROUP BY CUSTOMER_ID;

SELECT * FROM SALES_DATAVASE_NOV.ANALYTICS_LAYER.MV_CUSTOMER_SEGMENT;

-- CREATE FINAL REPORT FOR ANALYSIS

CREATE TABLE SALES_DATAVASE_NOV.ANALYTICS_LAYER.FINAL_SALES_REPORT AS
SELECT
    S.SALES_MONTH,
    C.CUSTOMER_CATEGORY,
    SUM(S.TOTAL_REVENUE) AS TOTAL_SALES
FROM SALES_DATAVASE_NOV.ANALYTICS_LAYER.SALES_AGGREGATE S
JOIN SALES_DATAVASE_NOV.ANALYTICS_LAYER.MV_CUSTOMER_SEGMENT C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY S.SALES_MONTH, C.CUSTOMER_CATEGORY
ORDER BY S.SALES_MONTH;


SELECT * FROM SALES_DATAVASE_NOV.ANALYTICS_LAYER.FINAL_SALES_REPORT;
